// <auto-generated />
using System;
using BackEndAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEndAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20250917022056_estadoReserva")]
    partial class estadoReserva
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEndAPI.Models.Caja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("BackEndAPI.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProducto");

                    b.ToTable("Categorias_Productos");
                });

            modelBuilder.Entity("BackEndAPI.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("BackEndAPI.Models.EstadoReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadoReserva");
                });

            modelBuilder.Entity("BackEndAPI.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("BackEndAPI.Models.MenuProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("IdMenu")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdMenu");

                    b.HasIndex("IdProducto");

                    b.ToTable("Menus_Productos");
                });

            modelBuilder.Entity("BackEndAPI.Models.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoParaPedir")
                        .HasColumnType("text");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("PersonaId");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Opcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioExtra")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.ToTable("Opciones");
                });

            modelBuilder.Entity("BackEndAPI.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoDeServicio")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("RolId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("RolId");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathImagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("BackEndAPI.Models.ProductosPorVisita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdVisita")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PrecioDelMomento")
                        .HasColumnType("double precision");

                    b.Property<double>("PrecioTotal")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IdVisita");

                    b.ToTable("ProductosPorVisita");
                });

            modelBuilder.Entity("BackEndAPI.Models.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("integer");

                    b.Property<int>("EstadoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdMesa")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("IdMesa");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rol");
                });

            modelBuilder.Entity("BackEndAPI.Models.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("PersonaId");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("BackEndAPI.Models.Visita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdCaja")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdMesa")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdMesa");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Caja", b =>
                {
                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Cajas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BackEndAPI.Models.CategoriaProducto", b =>
                {
                    b.HasOne("BackEndAPI.Models.Categoria", "Categoria")
                        .WithMany("CategoriaProductos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Producto", "Producto")
                        .WithMany("CategoriaProductos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BackEndAPI.Models.Menu", b =>
                {
                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Menus")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BackEndAPI.Models.MenuProducto", b =>
                {
                    b.HasOne("BackEndAPI.Models.Menu", "Menu")
                        .WithMany("MenuProductos")
                        .HasForeignKey("IdMenu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Producto", "Producto")
                        .WithMany("MenuProductos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BackEndAPI.Models.Mesa", b =>
                {
                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Mesas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Persona", "Persona")
                        .WithMany("Mesas")
                        .HasForeignKey("PersonaId");

                    b.Navigation("Persona");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BackEndAPI.Models.Opcion", b =>
                {
                    b.HasOne("BackEndAPI.Models.Producto", "Producto")
                        .WithMany("Opciones")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BackEndAPI.Models.Persona", b =>
                {
                    b.HasOne("BackEndAPI.Models.Empresa", "Empresa")
                        .WithMany("Personas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("BackEndAPI.Models.ProductosPorVisita", b =>
                {
                    b.HasOne("BackEndAPI.Models.Visita", "Visita")
                        .WithMany("ProductosPorVisita")
                        .HasForeignKey("IdVisita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("BackEndAPI.Models.Reserva", b =>
                {
                    b.HasOne("BackEndAPI.Models.EstadoReserva", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Mesa", "Mesa")
                        .WithMany("Reservas")
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("BackEndAPI.Models.Sucursal", b =>
                {
                    b.HasOne("BackEndAPI.Models.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Persona", null)
                        .WithMany("Sucursales")
                        .HasForeignKey("PersonaId");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BackEndAPI.Models.Visita", b =>
                {
                    b.HasOne("BackEndAPI.Models.Caja", "Caja")
                        .WithMany("Visitas")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Mesa", "Mesa")
                        .WithMany("Visitas")
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("BackEndAPI.Models.Caja", b =>
                {
                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Categoria", b =>
                {
                    b.Navigation("CategoriaProductos");
                });

            modelBuilder.Entity("BackEndAPI.Models.Empresa", b =>
                {
                    b.Navigation("Personas");

                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("BackEndAPI.Models.Menu", b =>
                {
                    b.Navigation("MenuProductos");
                });

            modelBuilder.Entity("BackEndAPI.Models.Mesa", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Persona", b =>
                {
                    b.Navigation("Mesas");

                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("BackEndAPI.Models.Producto", b =>
                {
                    b.Navigation("CategoriaProductos");

                    b.Navigation("MenuProductos");

                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("BackEndAPI.Models.Sucursal", b =>
                {
                    b.Navigation("Cajas");

                    b.Navigation("Menus");

                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Visita", b =>
                {
                    b.Navigation("ProductosPorVisita");
                });
#pragma warning restore 612, 618
        }
    }
}
