// <auto-generated />
using System;
using BackEndAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackEndAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260828132818_AddQzPrintingStations")]
    partial class AddQzPrintingStations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackEndAPI.ARCA.Clases.FETokenAuth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sign")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FETokenAuths");
                });

            modelBuilder.Entity("BackEndAPI.ARCA.Clases.FacturaElectronica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CAE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CAEFechaEmision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CAEFechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonSolicitud")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("NumeroComprobante")
                        .HasColumnType("bigint");

                    b.Property<int>("PuntoVenta")
                        .HasColumnType("integer");

                    b.Property<int>("TipoComprobante")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<string>("XmlRespuesta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FacturasElectronicas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Auditorias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Anterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Posterior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tabla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("BackEndAPI.Models.Caja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Diferencia")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoActual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoApertura")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MontoCierre")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal", "FechaCierre");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("BackEndAPI.Models.CuentaCorriente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("numeric");

                    b.Property<string>("Domicilo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CuentasCorrientes");
                });

            modelBuilder.Entity("BackEndAPI.Models.DeliveryAndTakeaway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<bool>("Entregado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdCadete")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid");

                    b.Property<int?>("IdTipoEnvio")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdVisita")
                        .HasColumnType("uuid");

                    b.Property<string>("Indicaciones")
                        .HasColumnType("text");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioEnvio")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("numeric");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<decimal>("precioProductos")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdCadete");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdTipoEnvio");

                    b.HasIndex("IdVisita");

                    b.ToTable("DeliveriesTakeaways");
                });

            modelBuilder.Entity("BackEndAPI.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<long>("Cuit")
                        .HasColumnType("bigint");

                    b.Property<string[]>("Emails")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("IdTipoSubscripcion")
                        .HasColumnType("smallint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string[]>("Telefonos")
                        .HasColumnType("text[]");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ubicacionCert")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdTipoSubscripcion");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("BackEndAPI.Models.EstadoReserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EstadoReservas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Pendiente"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Confirmada"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cancelada"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Completada"
                        });
                });

            modelBuilder.Entity("BackEndAPI.Models.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("BackEndAPI.Models.Mesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<string>("CodigoParaPedir")
                        .HasColumnType("text");

                    b.Property<Guid?>("IdPlano")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("h")
                        .HasColumnType("real");

                    b.Property<float>("w")
                        .HasColumnType("real");

                    b.Property<float>("x")
                        .HasColumnType("real");

                    b.Property<float>("y")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("IdPlano");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("BackEndAPI.Models.MovimientoCaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Facturado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdCaja")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdFactura")
                        .HasColumnType("uuid");

                    b.Property<int>("IdTipoMovimientoCaja")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IdVisita")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoAbonado")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Vuelto")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdTipoMovimientoCaja");

                    b.HasIndex("IdVisita");

                    b.HasIndex("IdCaja", "FechaMovimiento");

                    b.ToTable("MovimientosCajas");
                });

            modelBuilder.Entity("BackEndAPI.Models.MovimientoStock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Canal")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdMesa")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdStockProductoSucursal")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdVisita")
                        .HasColumnType("uuid");

                    b.Property<string>("Motivo")
                        .HasColumnType("text");

                    b.Property<string>("NombreMesa")
                        .HasColumnType("text");

                    b.Property<string>("NombreMozo")
                        .HasColumnType("text");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("integer");

                    b.Property<int>("StockPosterior")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdStockProductoSucursal");

                    b.HasIndex("IdVisita");

                    b.ToTable("MovimientosStock", t =>
                        {
                            t.HasCheckConstraint("CK_MovimientosStock_Canal", "\"Canal\" IN (0, 1, 2, 3)");

                            t.HasCheckConstraint("CK_MovimientosStock_ContextoCanal", "\"Canal\" = 1 OR (\"IdMesa\" IS NULL AND \"NombreMesa\" IS NULL AND \"NombreMozo\" IS NULL)");
                        });
                });

            modelBuilder.Entity("BackEndAPI.Models.MovimientosCuentaCorriente", b =>
                {
                    b.Property<Guid>("IdCuentaCorriente")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdMovimientoCaja")
                        .HasColumnType("uuid");

                    b.HasKey("IdCuentaCorriente", "IdMovimientoCaja");

                    b.HasIndex("IdMovimientoCaja");

                    b.ToTable("MovimientosCuentaCorriente");
                });

            modelBuilder.Entity("BackEndAPI.Models.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CodigoDeServicio")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IdSucursal")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("PersonajeId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Personas", t =>
                        {
                            t.HasCheckConstraint("CK_Personas_PersonajeId", "\"PersonajeId\" BETWEEN 0 AND 9");
                        });
                });

            modelBuilder.Entity("BackEndAPI.Models.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Detalles")
                        .HasColumnType("text");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("BackEndAPI.Models.Printing.PrinterAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Copies")
                        .HasColumnType("smallint");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<short>("PaperWidthMm")
                        .HasColumnType("smallint");

                    b.Property<string>("QzPrinterName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("StationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "Role")
                        .IsUnique();

                    b.ToTable("PrinterAssignments", t =>
                        {
                            t.HasCheckConstraint("CK_PrinterAssignments_Copies", "\"Copies\" BETWEEN 1 AND 10");

                            t.HasCheckConstraint("CK_PrinterAssignments_PaperWidthMm", "\"PaperWidthMm\" IN (58, 80)");
                        });
                });

            modelBuilder.Entity("BackEndAPI.Models.Printing.PrintingStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientInstallationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal", "ClientInstallationId")
                        .IsUnique();

                    b.ToTable("PrintingStations");
                });

            modelBuilder.Entity("BackEndAPI.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasColumnType("text");

                    b.Property<decimal?>("CostoProduccion")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathImagen")
                        .HasColumnType("text");

                    b.Property<decimal>("PorcentajeIVA")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PrecioNeto")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("BackEndAPI.Models.ProductosPorVisita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalles")
                        .HasColumnType("text");

                    b.Property<bool>("EstadoPagado")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoPedido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaAgregado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("IVADelMomento")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("IdMovimientoCaja")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdProducto")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdVisita")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioDelMomento")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVisita");

                    b.ToTable("ProductosPorVisita");
                });

            modelBuilder.Entity("BackEndAPI.Models.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CantidadDePersonas")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdEstadoReserva")
                        .HasColumnType("integer");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid");

                    b.Property<string>("MesaReserva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreReserva")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdEstadoReserva");

                    b.HasIndex("IdSucursal");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Mozo"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Cadete"
                        });
                });

            modelBuilder.Entity("BackEndAPI.Models.StockProductoSucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantidadActual")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadMinima")
                        .HasColumnType("integer");

                    b.Property<bool>("ControlaStock")
                        .HasColumnType("boolean");

                    b.Property<bool>("EnviarAlerta")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdProducto")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdSucursal")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdProducto", "IdSucursal")
                        .IsUnique();

                    b.ToTable("StockProductosSucursales");
                });

            modelBuilder.Entity("BackEndAPI.Models.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<Guid>("IdEmpresa")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("BackEndAPI.Models.TipoEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TipoEnvios");
                });

            modelBuilder.Entity("BackEndAPI.Models.TipoMovimientoCaja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Entorno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsEfectivo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsIngreso")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoMovimientosCajas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Entorno = "Movimiento",
                            EsEfectivo = true,
                            EsIngreso = true,
                            Nombre = "Ingreso de Efectivo"
                        },
                        new
                        {
                            Id = 2,
                            Entorno = "Movimiento",
                            EsEfectivo = true,
                            EsIngreso = false,
                            Nombre = "Retiro de Efectivo"
                        },
                        new
                        {
                            Id = 3,
                            Entorno = "Movimiento",
                            EsEfectivo = true,
                            EsIngreso = false,
                            Nombre = "Pago Proveedor con Efectivo"
                        },
                        new
                        {
                            Id = 4,
                            Entorno = "Movimiento",
                            EsEfectivo = false,
                            EsIngreso = false,
                            Nombre = "Pago Proveedor con Transferencia"
                        },
                        new
                        {
                            Id = 5,
                            Entorno = "Movimiento",
                            EsEfectivo = false,
                            EsIngreso = false,
                            Nombre = "Pago Proveedor con Tarjeta De Credito/Debito"
                        },
                        new
                        {
                            Id = 6,
                            Entorno = "Movimiento",
                            EsEfectivo = true,
                            EsIngreso = false,
                            Nombre = "Pago Sueldos con Efectivo"
                        },
                        new
                        {
                            Id = 7,
                            Entorno = "Movimiento",
                            EsEfectivo = false,
                            EsIngreso = false,
                            Nombre = "Pago Sueldos con Transferencia"
                        },
                        new
                        {
                            Id = 8,
                            Entorno = "Movimiento",
                            EsEfectivo = false,
                            EsIngreso = false,
                            Nombre = "Pago Sueldos con Tarjeta De Credito/Debito"
                        },
                        new
                        {
                            Id = 9,
                            Entorno = "Movimiento",
                            EsEfectivo = true,
                            EsIngreso = false,
                            Nombre = "Gastos con Efectivo"
                        },
                        new
                        {
                            Id = 10,
                            Entorno = "Movimiento",
                            EsEfectivo = false,
                            EsIngreso = false,
                            Nombre = "Gastos con Transferencia"
                        },
                        new
                        {
                            Id = 11,
                            Entorno = "Movimiento",
                            EsEfectivo = false,
                            EsIngreso = false,
                            Nombre = "Gastos con Tarjeta De Credito/Debito"
                        },
                        new
                        {
                            Id = 12,
                            Entorno = "CuentaCorriente",
                            EsEfectivo = true,
                            EsIngreso = true,
                            Nombre = "Cobro con Efectivo"
                        },
                        new
                        {
                            Id = 13,
                            Entorno = "CuentaCorriente",
                            EsEfectivo = false,
                            EsIngreso = true,
                            Nombre = "Cobro con Transferencia"
                        },
                        new
                        {
                            Id = 14,
                            Entorno = "CuentaCorriente",
                            EsEfectivo = false,
                            EsIngreso = true,
                            Nombre = "Cobro con QR"
                        },
                        new
                        {
                            Id = 15,
                            Entorno = "CuentaCorriente",
                            EsEfectivo = false,
                            EsIngreso = true,
                            Nombre = "Cobro con Tarjeta De Credito/Debito"
                        },
                        new
                        {
                            Id = 16,
                            Entorno = "CuentaCorriente",
                            EsEfectivo = false,
                            EsIngreso = false,
                            Nombre = "Gastos"
                        },
                        new
                        {
                            Id = 17,
                            Entorno = "Ventas",
                            EsEfectivo = true,
                            EsIngreso = true,
                            Nombre = "Cobro con Efectivo"
                        },
                        new
                        {
                            Id = 18,
                            Entorno = "Ventas",
                            EsEfectivo = false,
                            EsIngreso = true,
                            Nombre = "Cobro con Tarjeta de Credito/Debito"
                        },
                        new
                        {
                            Id = 19,
                            Entorno = "Ventas",
                            EsEfectivo = false,
                            EsIngreso = true,
                            Nombre = "Cobro con Transferencia"
                        },
                        new
                        {
                            Id = 20,
                            Entorno = "Ventas",
                            EsEfectivo = false,
                            EsIngreso = true,
                            Nombre = "Cobro con QR"
                        },
                        new
                        {
                            Id = 21,
                            Entorno = "Ventas",
                            EsEfectivo = true,
                            EsIngreso = false,
                            Nombre = "Reembolso con Efectivo"
                        },
                        new
                        {
                            Id = 22,
                            Entorno = "Ventas",
                            EsEfectivo = false,
                            EsIngreso = false,
                            Nombre = "Reembolso Tarjeta de Credito/Debito"
                        },
                        new
                        {
                            Id = 23,
                            Entorno = "Ventas",
                            EsEfectivo = false,
                            EsIngreso = false,
                            Nombre = "Reembolso Transferencia"
                        },
                        new
                        {
                            Id = 24,
                            Entorno = "Ventas",
                            EsEfectivo = false,
                            EsIngreso = false,
                            Nombre = "Reembolso QR"
                        });
                });

            modelBuilder.Entity("BackEndAPI.Models.Visita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdCaja")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdMesa")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdMozo")
                        .HasColumnType("uuid");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdMozo");

                    b.HasIndex("IdCaja", "FechaHora");

                    b.ToTable("Visitas");
                });

            modelBuilder.Entity("CategoriaProducto", b =>
                {
                    b.Property<Guid>("CategoriasId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductosId")
                        .HasColumnType("uuid");

                    b.HasKey("CategoriasId", "ProductosId");

                    b.HasIndex("ProductosId");

                    b.ToTable("CategoriaProducto");
                });

            modelBuilder.Entity("MenuProducto", b =>
                {
                    b.Property<Guid>("MenusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductosId")
                        .HasColumnType("uuid");

                    b.HasKey("MenusId", "ProductosId");

                    b.HasIndex("ProductosId");

                    b.ToTable("MenuProducto");
                });

            modelBuilder.Entity("TipoSubscripcion", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string[]>("Features")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("TipoSubscriptions");
                });

            modelBuilder.Entity("BackEndAPI.Models.Caja", b =>
                {
                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Cajas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BackEndAPI.Models.DeliveryAndTakeaway", b =>
                {
                    b.HasOne("BackEndAPI.Models.Persona", "Cadete")
                        .WithMany()
                        .HasForeignKey("IdCadete");

                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Deliveries")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.TipoEnvio", "TipoEnvio")
                        .WithMany()
                        .HasForeignKey("IdTipoEnvio")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEndAPI.Models.Visita", "Visita")
                        .WithMany()
                        .HasForeignKey("IdVisita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadete");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoEnvio");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("BackEndAPI.Models.Empresa", b =>
                {
                    b.HasOne("TipoSubscripcion", "TipoSubscripcion")
                        .WithMany()
                        .HasForeignKey("IdTipoSubscripcion");

                    b.Navigation("TipoSubscripcion");
                });

            modelBuilder.Entity("BackEndAPI.Models.Menu", b =>
                {
                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Menus")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BackEndAPI.Models.Mesa", b =>
                {
                    b.HasOne("BackEndAPI.Models.Plano", "Plano")
                        .WithMany("Mesas")
                        .HasForeignKey("IdPlano")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plano");
                });

            modelBuilder.Entity("BackEndAPI.Models.MovimientoCaja", b =>
                {
                    b.HasOne("BackEndAPI.Models.Caja", "Caja")
                        .WithMany("MovimientosCaja")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.ARCA.Clases.FacturaElectronica", "facturaElectronica")
                        .WithMany()
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEndAPI.Models.TipoMovimientoCaja", "TipoMovimientoCaja")
                        .WithMany()
                        .HasForeignKey("IdTipoMovimientoCaja")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Visita", "Visita")
                        .WithMany("Pagos")
                        .HasForeignKey("IdVisita")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Caja");

                    b.Navigation("TipoMovimientoCaja");

                    b.Navigation("Visita");

                    b.Navigation("facturaElectronica");
                });

            modelBuilder.Entity("BackEndAPI.Models.MovimientoStock", b =>
                {
                    b.HasOne("BackEndAPI.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEndAPI.Models.StockProductoSucursal", "StockProductoSucursal")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdStockProductoSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Visita", "Visita")
                        .WithMany()
                        .HasForeignKey("IdVisita")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mesa");

                    b.Navigation("StockProductoSucursal");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("BackEndAPI.Models.MovimientosCuentaCorriente", b =>
                {
                    b.HasOne("BackEndAPI.Models.CuentaCorriente", "CuentaCorriente")
                        .WithMany("Movimientos")
                        .HasForeignKey("IdCuentaCorriente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.MovimientoCaja", "MovimientoCaja")
                        .WithMany()
                        .HasForeignKey("IdMovimientoCaja")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaCorriente");

                    b.Navigation("MovimientoCaja");
                });

            modelBuilder.Entity("BackEndAPI.Models.Persona", b =>
                {
                    b.HasOne("BackEndAPI.Models.Empresa", "Empresa")
                        .WithMany("Personas")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");

                    b.Navigation("Rol");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BackEndAPI.Models.Plano", b =>
                {
                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Planos")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BackEndAPI.Models.Printing.PrinterAssignment", b =>
                {
                    b.HasOne("BackEndAPI.Models.Printing.PrintingStation", "Station")
                        .WithMany("Assignments")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("BackEndAPI.Models.Printing.PrintingStation", b =>
                {
                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany("PrintingStations")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BackEndAPI.Models.ProductosPorVisita", b =>
                {
                    b.HasOne("BackEndAPI.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEndAPI.Models.Visita", "Visita")
                        .WithMany("Productos")
                        .HasForeignKey("IdVisita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Visita");
                });

            modelBuilder.Entity("BackEndAPI.Models.Reserva", b =>
                {
                    b.HasOne("BackEndAPI.Models.EstadoReserva", "Estado")
                        .WithMany()
                        .HasForeignKey("IdEstadoReserva")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany("Reservas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BackEndAPI.Models.StockProductoSucursal", b =>
                {
                    b.HasOne("BackEndAPI.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("BackEndAPI.Models.Sucursal", b =>
                {
                    b.HasOne("BackEndAPI.Models.Empresa", "Empresa")
                        .WithMany("Sucursales")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("BackEndAPI.Models.Visita", b =>
                {
                    b.HasOne("BackEndAPI.Models.Caja", "Caja")
                        .WithMany("Visitas")
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Mesa", "Mesa")
                        .WithMany()
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BackEndAPI.Models.Persona", "Mozo")
                        .WithMany()
                        .HasForeignKey("IdMozo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Caja");

                    b.Navigation("Mesa");

                    b.Navigation("Mozo");
                });

            modelBuilder.Entity("CategoriaProducto", b =>
                {
                    b.HasOne("BackEndAPI.Models.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MenuProducto", b =>
                {
                    b.HasOne("BackEndAPI.Models.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEndAPI.Models.Producto", null)
                        .WithMany()
                        .HasForeignKey("ProductosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndAPI.Models.Caja", b =>
                {
                    b.Navigation("MovimientosCaja");

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("BackEndAPI.Models.CuentaCorriente", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("BackEndAPI.Models.Empresa", b =>
                {
                    b.Navigation("Personas");

                    b.Navigation("Sucursales");
                });

            modelBuilder.Entity("BackEndAPI.Models.Plano", b =>
                {
                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Printing.PrintingStation", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("BackEndAPI.Models.StockProductoSucursal", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("BackEndAPI.Models.Sucursal", b =>
                {
                    b.Navigation("Cajas");

                    b.Navigation("Deliveries");

                    b.Navigation("Menus");

                    b.Navigation("Planos");

                    b.Navigation("PrintingStations");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("BackEndAPI.Models.Visita", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
