import { apiAdministrativa, apiSucursal } from './clienteImpresion';
import { obtenerIdInstalacionCliente, obtenerTokenAccesoEstacion, obtenerCredencialEstacion, guardarEstacionRegistrada, guardarCredencialEstacion, guardarSesionEstacion } from './almacenamientoEstacion';
let registro = null;
export async function obtenerEstacionActual(id = obtenerIdInstalacionCliente()) { return guardarEstacionRegistrada((await apiSucursal.get('impresion/estaciones/actual', { params: { idInstalacionCliente: id } })).data); }
export async function registrarEstacionActual(nombre) { const id = obtenerIdInstalacionCliente(); let valor = nombre?.trim(); if (!valor) { try { valor = (await obtenerEstacionActual(id)).nombre; } catch (e) { if (e.response?.status !== 404) throw e; } } return guardarEstacionRegistrada((await apiSucursal.post('impresion/estaciones/registrar', { idInstalacionCliente: id, nombre: valor || `Caja ${id.slice(0, 8)}` })).data); }
export async function darAltaEstacionActual(nombre) { const { data } = await apiAdministrativa.post('impresion/estaciones/alta', { idInstalacionCliente: obtenerIdInstalacionCliente(), nombre }); guardarEstacionRegistrada(data.estacion); let credencial = data.credencial; if (!credencial && obtenerCredencialEstacion()) { try { await crearSesionEstacion(); return data.estacion; } catch { /* rotar */ } } if (!credencial) credencial = (await apiAdministrativa.post(`impresion/estaciones/${data.estacion.id}/rotar-credencial`)).data.credencial; if (credencial) guardarCredencialEstacion(credencial); return data.estacion; }
export async function crearSesionEstacion() { const credencial = obtenerCredencialEstacion(); if (!credencial) throw new Error('CREDENCIAL_ESTACION_FALTANTE'); return guardarSesionEstacion((await apiAdministrativa.post('impresion/estaciones/sesion', { idSucursal: localStorage.getItem('idSucursal'), idInstalacionCliente: obtenerIdInstalacionCliente(), credencial })).data); }
export async function asegurarSesionEstacion() { return obtenerTokenAccesoEstacion() || (await crearSesionEstacion()).tokenAcceso; }
export function asegurarEstacionActualRegistrada(nombre) { if (!registro) registro = registrarEstacionActual(nombre).finally(() => { registro = null; }); return registro; }
export async function registrarLatidoEstacion(id) { return (await apiSucursal.post(`impresion/estaciones/${id}/latido`)).data; }
